services:
  back:
    build:
      dockerfile: back/Dockerfile
    command: >
      sh -c "alembic upgrade head &&
          gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --reload --bind=0.0.0.0:8000"
    volumes:
      - ./back/app:/code/app
      - ./back/migrations:/code/migrations
    ports:
      - 8000:8000
    env_file:
      - ./back/.env.prod
    networks:
      - local
    depends_on:
      - postgres
  
  front:
    build: 
      dockerfile: front/Dockerfile
    volumes:
        - ./front:/next_app/
    ports:
      - "3000:3000"
    networks:
      - local
    depends_on:
      - back
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./back/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - local
      
networks:
  local:
    driver: bridge
  
volumes:
  postgres_data:
