version: '3.8'


services:
  web:
    build: 
      dockerfile: back/Dockerfile
    command: >
      sh -c "alembic upgrade head &&
            uvicorn app.main:app --reload --host '0.0.0.0'"
    volumes:
      - ./back/app:/code/app
      - ./back/migrations:/code/migrations
    ports:
      - 8000:8000
    env_file:
      - ./back/.env
    networks:
      - local
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./back/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - local
      
networks:
  local:
    driver: bridge
  
volumes:
  postgres_data:
